### ISSUE TITLE
CRAN notice

### ISSUE THREAD

**Issue by vgherard** [djwtouw/CCMMR#4]
Dear package maintainers, you may have received a notice about CRAN package [{r2r}](https://github.com/vgherard/r2r) - of which I'm author and upon which your package depends - being scheduled for removal from CRAN on the 28/11/2024.

Just wanted to let you know that I'm aware of the issue (see https://github.com/vgherard/r2r/issues/9) and I plan to fix this in the next few working days.

Thanks!

**Comment by vgherard** [comment]
I just checked on CRAN that (apparently) your package does not depend anymore on `r2r`. If this is the case, sorry for the hassle.

**Comment by djwtouw** [comment]
Hi, thank you for notifying us. We indeed tweaked the package yesterday, these changes are now also available on GitHub. We appreciate you reaching out to us!
